### ISSUE TITLE
Missing Word

### ISSUE THREAD

**Issue by Nikki-Luoma** [liux2/about-me#3]
In the fifth line you wrote, "my father thought I could addicted to computer games and the misleading information." I think you should add "become" between "could" and "addicted". Also, I think you should explain what you mean of misleading information.

**Comment by myersj451** [comment]
I agree with this change of adding more information to provide better context.

**Comment by liux2** [comment]
I have changed the sentence to " The reason is, my father thought I could get addicted to computer games and he also thought I could have some bad influence from the internet, such as become violent and impolite."
