### ISSUE TITLE
Sentence Revision 

### ISSUE THREAD

**Issue by Nikki-Luoma** [liux2/about-me#6]
"After my breaking the limitation of internet and 
electronic devices, I accessed more and more information about software, computer, and systems." The first part of the sentence does not sound right and is confusing. I would recommend changing it.

**Comment by myersj451** [comment]
Just take out "my" in the first half of the sentence. Consider: "After breaking the limitations of the internet and electronic devices..."

**Comment by liux2** [comment]
I have changed sentence to "After gaining access to the internet and electronic devices, I learned more and more information about software, computers, and systems. "
